import numpy as np
print("Array with all zeroes: ")
arr0 = np.zeros((3,3))
print(arr0)
print("Array with all ones: ")
arr1 = np.ones((3,3))
print(arr1)
print("Identity matrix: ")
arr2 = np.identity(3)
print(arr2)
print("1-D array: ")
arr1D = np.array([1,2,3,4,5])
print(arr1D)
print("No. of Dimensions: ",arr1D.ndim)
print("2-D array: ")
arr2D = np.array([[1,2,3],[4,5,6]])
print(arr2D)
print("No. of Dimensions: ",arr2D.ndim)
print("3-D array: ")
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,2,4]]])
print(arr3D)
print("No. of Dimensions: ",arr3D.ndim)
print("N-D array: ")
arrND = np.array([1, 2, 3, 4], ndmin=5)
print(arrND)
print("No. of Dimensions: ",arrND.ndim)

rand_arr = np.random.rand(2,3)
print("Random array with 2-rows and 3-columns: ")
print(rand_arr)
print("Reversed matrix: ")
rev_arr = rand_arr[::-1]
print(rev_arr)

rand_arr1 = np.random.rand(4,4)
print("Created a random 4X4 matrix: ")
print(rand_arr1)
print("Reshaping the array to 3X2 matrix: ")
print(rand_arr1.reshape(3,2))
