import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
add = np.add(arr1,arr2)
print("Addition of arrays: ")
print(add)
sub = np.subtract(arr1,arr2)
print("Substraction of arrays: ")
print(sub)
mult = np.multiply(arr1,arr2)
print("Multiplication of arrays: ")
print(mult)
div = np.divide(arr1,arr2)
print("Division of arrays: ")
print(div)
transpose = np.transpose(arr1)
print("Transpose of arrays: ")
print(transpose)