A = {1,2,3,4,5}
B = {6,7,8}
print("After A.add(6): ")
A.add(6)
print(A)
print("After A.update(B): ")
A.update(B)
print(A)
print("After A.remove(6): ")
A.remove(6)
print(A)
print("After A.discard(5): ")
A.discard(5)
print(A)
print("After A.pop(): ")
A.pop()
print(A)
print("After A.isdisjoint(B): ")
print(A.isdisjoint(B))
print("After A.issubset(B): ")
print(A.issubset(B))
print("After A.clear(): ")
print(A.clear())