import stack_module_custom as stk
stack=stk.getStack()
stk.Push(stack,5)
stk.Push(stack,3)
stk.Push(stack,2)
stk.Push(stack,6)
stk.Push(stack,7)
print(stack)
stk.Pop(stack)
print(stack)
stk.Push(stack,'num')
print(stack)
print(stk.isempty(stack))
print(stk.Top(stack))