file = open("Student.txt",'w')
a1 = input("Name: ")
file.write(a1)
a2 = input("Class: ")
file.write(a2)
a3 = input("Roll No.: ")
file.write(a3)
file.close()
file1 = open("Student.txt",'r')
print(file1.read())
file1.close()
